services:
  nginx:
    image: nginx:alpine
    container_name: lc-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./client/dist/client/browser:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - backend
    networks:
      - localcrag-network

  certbot:
    image: certbot/certbot
    container_name: lc-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - backend
    networks:
      - localcrag-network

  backend:
    build:
      dockerfile: Dockerfile-backend
    container_name: lc-backend
    volumes:
      - ./server/src:/app/src
    depends_on:
      - db
      - minio
    networks:
      - localcrag-network
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - SQLALCHEMY_DATABASE_URI=postgresql://localcrag_user:${DB_PASSWORD}@db:5432/localcrag
      - LOCALCRAG_CONFIG=/app/src/config/dev.cfg
      - SPACES_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - SPACES_SECRET_KEY=${MINIO_SECRET_KEY}
      - SPACES_ENDPOINT=http://minio:9000
      - SPACES_BUCKET=localcrag
      - SPACES_ACCESS_ENDPOINT=https://${HOSTNAME}/minio
      - SPACES_ADDRESSING=path
      - SMTP_HOST=smtp.strato.de
      - SMTP_PORT=465
      - SMTP_TYPE=smtps
      - PYTHONPATH=/app/src

  db:
    image: postgres:17.4-alpine
    container_name: lc-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=localcrag
      - POSTGRES_USER=localcrag_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - localcrag-network

  minio:
    image: pgsty/minio:RELEASE.2026-03-25T00-00-00Z
    container_name: lc-minio
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      - MINIO_INIT_BUCKET=localcrag
    command: server /data --address :9000 --console-address :9001
    networks:
      - localcrag-network
    entrypoint: |  # Adopted from https://stackoverflow.com/a/78580294
      /bin/sh -c '
        isAlive() { curl -sf http://127.0.0.1:9000/minio/health/live; }
        minio $$0 "$$@" --quiet & echo $$! > /tmp/minio.pid
        while ! isAlive; do sleep 0.1; done
        mc alias set minio http://127.0.0.1:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD
        mc mb minio/$$MINIO_INIT_BUCKET || true
        mc anonymous set public minio/$$MINIO_INIT_BUCKET
        kill -s INT $$(cat /tmp/minio.pid) && rm /tmp/minio.pid
        while isAlive; do sleep 0.1; done
        exec minio $$0 "$$@"
      '
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  localcrag-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mofrim/goewalddb/data/postgres-data
  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mofrim/goewalddb/data/minio-data
